version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - run:
          name: Build docker image
          command: |
            cd series7/test && docker-compose build
      - run:
          name: Run tests
          command: |
            cd series7/test && docker-compose up test
      - run:
          name: Push to dockerhub
          command: |
            docker images

            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWD

            docker tag test_web $DOCKERHUB_USER/$DOCKERHUB_REPO:latest
            docker push $DOCKERHUB_USER/$DOCKERHUB_REPO:latest

            docker tag test_web $DOCKERHUB_USER/$DOCKERHUB_REPO:circle-${CIRCLE_BUILD_NUM}
            docker push $DOCKERHUB_USER/$DOCKERHUB_REPO:circle-${CIRCLE_BUILD_NUM}

      - run:
         name: Deploy to EB
         command: |
            pip install awsebcli --upgrade

            if ! test -f ".elasticbeanstalk/config.yml"; then
              echo -e "\n\n" | eb init tarusd-sd -v -r ap-northeast-1
            fi
            
            eb use taru-sd-stg
            eb deploy -l circle-${CIRCLE_BUILD_NUM}
